'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Product
    Public Property Id As Integer
    Public Property ProductName As String
    Public Property Quality As Nullable(Of Integer)
    Public Property CatId As Nullable(Of Integer)

    Public Overridable Property tbl_Category As tbl_Category

End Class
